sudo: required
dist: precise
language: android
android:
  components:
  - platform-tools
  - android-22
  - build-tools-23.0.1
# branches:
#   only:
#   - master
before_install:
  - export DIR=$PWD
  - echo $DIR
  - npm config set strict-ssl false 
  - nvm install 0.12.7
  - node -v
  - npm install -g cordova@5.1.1
  - cordova -v
  - cd /home/travis/.nvm/versions/node/v0.12.7/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/ && npm install request@2.88.0
  - cd $DIR
script:
  - make debug
after_success:
  - echo "Build success!"

jobs:
  include:
    # - script: echo "Running unit tests"
    - stage: GitHub Release
      script: 
        - echo "Deploying to GitHub releases ..."
        # - make debug
      deploy:
        provider: releases
        file: ./package.json
        api_key: $GITHUB_PERSONAL_TOKEN
        skip_cleanup: true
        branch: master
        on:
          tags: true