sudo: required
language: android
android:
  components:
  - build-tools-23.0.1
  - android-23
branches:
  only:
  - master
before_install:
  - which android
  - ls /usr/local/android-sdk/
  - ls /usr/local/android-sdk/build-tools/
  - ls /usr/local/android-sdk/build-tools/23.0.1/
  - ls /usr/local/android-sdk/build-tools/23.0.1/zipalign
  # - ls $HOME/Library/Android/sdk/build-tools/
  # - ls $HOME/Library/Android/sdk/build-tools/23.0.1/
  # - ls $HOME/Library/Android/sdk/build-tools/23.0.1/zipalign
  - echo $PASSWORD
  - sudo apt-get install node
  # - node -v
  # - sudo apt-get install npm
  - npm config set strict-ssl false
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash
  - nvm install 0.12.7
  # - node -v
  - npm install -g cordova
  - bash install-qshell.sh || exit 1
  - export PATH=$PATH:$PWD/qiniu
  - qshell -h
script:
  - make debug
after_success:
  - bash upload.sh
  - echo $PASSWORD
  - ls $HOME/.gradle/caches/modules-2/files-2.1/org.xwalk/xwalk_core_library/17.46.448.10
