sudo: required
dist: trusty
language: android
android:
  components:
    - build-tools-23.0.1
    - android-23

branches:
  only:
    - master

before_install:
  - node -v
  - sudo apt-get install npm
  - npm config set strict-ssl false
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash
  - command -v nvm
  - nvm install 5.0
  - nvm ls
  - node -v
  - nvm use 5.8.0
  - node -v
  - sudo npm install -g cordova
  - bash install-qshell.sh || exit 1
  - export PATH=$PATH:$PWD/qiniu
  - qshell -h

script:
  - make debug

after_success:
  - bash upload.sh
  - ls $HOME/.gradle/caches/modules-2/files-2.1/org.xwalk/xwalk_core_library/17.46.448.10
