sudo: required
language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository
    # - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17
before_install:
  - node -v
  - sudo apt-get install npm
  - npm config set strict-ssl false
  - sudo npm install n -g
  - sudo n 0.12.7
  - node -v
  - sudo npm install -g cordova
  - bash install-qshell.sh || exit 1
  - export PATH=$PATH:$PWD/qiniu
  - qshell -h
script:
  - make debug

after_success:
  - bash upload.sh
  - ls $HOME/.gradle/caches/modules-2/files-2.1/org.xwalk/xwalk_core_library/17.46.448.10
